# -*- coding: utf-8 -*-
"""data_integrity_checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbzJWRTRq9Av6iY_GxnySTi2PZvNL_Is
"""

import hashlib

# --- THE TOOL ---
def calculate_hash(message):
  """Generates a SHA-256 fingerprint for a text."""
  sha256_hash = hashlib.sha256()
  sha256_hash.update(message.encode('utf-8'))
  return sha256_hash.hexdigest()

print("--- BANK SECURITY SYSTEM: INTEGRITY CHECK ---")

# 1. The Original Instruction (Authorized)
original_data = "Transfer $5,000,000 to Olamide"
print(f"Original Data: {original_data}")
original_hash = calculate_hash(original_data)
print(f"Original Seal: {original_hash}")

print("\n...ATTACKER INTERCEPTS AND MODIFIES DATA ...\n")

# 2. The Tampered Instruction (Unauthorized)
received_data = "Transfer $5,000,000 to HACKER"
print(f"Received Data: {received_data}")
received_hash = calculate_hash(original_data)
print(f"Received Seal: {received_hash}")

# 3. The Audit Logic
print("\n--- RUNNING AUTOMATED AUDIT ---")
if original_hash == received_hash:
    print("[SUCCESS] Integrity Verified: Data matches exactly.")
else:
    print("[ALERT] INTEGRITY VIOLATION: The Digital Seal is BROKEN!")
    print("Action: Transaction Blocked.")